### ISSUE TITLE
[output overflow, print less text!]

### ISSUE THREAD

**Issue by Heyter** [perbone/luascript#16]
Godot 3.2
Windows 10

```
local class = require 'lua.class' -- Import the system class library
godot.Node2D = require 'godot.Node2D' -- Make sure to import the base class


local Node2d = class.extends(godot.Node2D) -- Create the user subclass

function Node2d:_ready()
	print('Hello world')
end

function Node2d:_process(delta)

end


return Node2d
```

**Comment by rawsp33d** [comment]
I'm guessing this was closed because it is lacking info, but I think I'm experiencing the same problem. Luascript kind of just constantly prints to the output pane, flooding it even when the game isn't running. When a game _is_ running, I can't see the output of my own print statements and I do see `[output overflow, print less text!]` printed at one point, before it gets flooded again.

Can these be disabled or debug only or something?

**Comment by perbone** [comment]
I guess it should be more log friendly. I'll make it obey the 'verbose' command line parameter. 
Would that be ok?

**Comment by rawsp33d** [comment]
Yeah that sounds great. Thanks!
