### ISSUE TITLE
Compiling for linux X11 ubuntu

### ISSUE THREAD

**Issue by arifnegh45** [perbone/luascript#20]
when i use this command
`scons platform=x11 module_luascript_enabled=yes`

i get this output

`scons: Reading SConscript files ...

scons: *** Illegal construction variable `module_luascript-master_enabled'
File "/home/adil/Desktop/godot-3.2.2-stable/SConstruct", line 227, in <module>`

**Comment by arifnegh45** [comment]
I got help from NeQs in the godot discord server and i get the error because luascript-master is an invalid module name so when i downloaded this repository i got the zip file luascript-master.zip so i changed the luascript-master name to luascript

**Comment by perbone** [comment]
That's great! Any further needed help let me know.
-- Perbone

**Comment by arifnegh45** [comment]
I do need more help building failed with this

https://pastebin.pl/view/48e840e2

**Comment by arifnegh45** [comment]
i used this command and i just read in the merror message that the use_lto failed so im trying it without that so il come back after i tried it without use_lto=yes
`scons -j 6 bits=64 module_luascript_enabled=yes use_lto=yes target=release_debug tools=yes platform=x11
`

**Comment by perbone** [comment]
That's interesting... never used LTO before as I think it's a release only optimization and I'm not there yet. Can't try this right now but eventually I will and I'll get back to you.
-- Perbone

**Comment by perbone** [comment]
So it seems LTO does not works. I have different errors from your though but can't finish the build as well. For the time being I would keep this optimization out of the build.
See my error log in the next coment.
-- Perbone

**Comment by perbone** [comment]
[ 99%] progress_finish(["progress_finish"], [])
[100%] Linking Static Library ==> modules/freetype/libfreetype_builtin.x11.tools.64.llvm.a
[100%] Ranlib Library         ==> modules/freetype/libfreetype_builtin.x11.tools.64.llvm.a
[100%] Linking Static Library ==> core/libcore.x11.tools.64.llvm.a
Ranlib Library         ==> core/libcore.x11.tools.64.llvm.a
[100%] Linking Program        ==> bin/godot.x11.tools.64.llvm

ld.lld: error: undefined symbol: register_module_types()
>>> referenced by main.cpp:1419 (main/main.cpp:1419)
>>>               lto.tmp:(Main::setup2(unsigned long))

ld.lld: error: undefined symbol: unregister_module_types()
>>> referenced by main.cpp:2250 (main/main.cpp:2250)
>>>               lto.tmp:(Main::cleanup())

ld.lld: error: undefined symbol: GDScriptTokenizerText::set_code(String const&)
>>> referenced by test_gdscript.cpp:985 (main/tests/test_gdscript.cpp:985)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token(int) const
>>> referenced by test_gdscript.cpp:987 (main/tests/test_gdscript.cpp:987)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:990 (main/tests/test_gdscript.cpp:990)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:992 (main/tests/test_gdscript.cpp:992)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1000 (main/tests/test_gdscript.cpp:1000)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1002 (main/tests/test_gdscript.cpp:1002)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1004 (main/tests/test_gdscript.cpp:1004)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1007 (main/tests/test_gdscript.cpp:1007)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token_identifier(int) const
>>> referenced by test_gdscript.cpp:991 (main/tests/test_gdscript.cpp:991)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token_constant(int) const
>>> referenced by test_gdscript.cpp:993 (main/tests/test_gdscript.cpp:993)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token_error(int) const
>>> referenced by test_gdscript.cpp:1001 (main/tests/test_gdscript.cpp:1001)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token_line(int) const
>>> referenced by test_gdscript.cpp:1003 (main/tests/test_gdscript.cpp:1003)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1009 (main/tests/test_gdscript.cpp:1009)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1011 (main/tests/test_gdscript.cpp:1011)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token_line_indent(int) const
>>> referenced by test_gdscript.cpp:1003 (main/tests/test_gdscript.cpp:1003)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token_built_in_func(int) const
>>> referenced by test_gdscript.cpp:1005 (main/tests/test_gdscript.cpp:1005)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptFunctions::get_func_name(GDScriptFunctions::Function)
>>> referenced by test_gdscript.cpp:1005 (main/tests/test_gdscript.cpp:1005)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:805 (main/tests/test_gdscript.cpp:805)
>>>               lto.tmp:(TestGDScript::_disassemble_class(Ref<GDScript> const&, Vector<String> const&))
>>> referenced by test_gdscript.cpp:140 (main/tests/test_gdscript.cpp:140)
>>>               lto.tmp:(TestGDScript::_parser_expr(GDScriptParser::Node const*))

ld.lld: error: undefined symbol: GDScriptTokenizer::get_token_name(GDScriptTokenizer::Token)
>>> referenced by test_gdscript.cpp:1007 (main/tests/test_gdscript.cpp:1007)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::get_token_column(int) const
>>> referenced by test_gdscript.cpp:1020 (main/tests/test_gdscript.cpp:1020)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptTokenizerText::advance(int)
>>> referenced by test_gdscript.cpp:1021 (main/tests/test_gdscript.cpp:1021)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptParser::GDScriptParser()
>>> referenced by test_gdscript.cpp:1027 (main/tests/test_gdscript.cpp:1027)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1044 (main/tests/test_gdscript.cpp:1044)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptParser::parse(String const&, String const&, bool, String const&, bool, Set<int, Comparator<int>, DefaultAllocator>*, bool)
>>> referenced by test_gdscript.cpp:1028 (main/tests/test_gdscript.cpp:1028)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1046 (main/tests/test_gdscript.cpp:1046)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptParser::get_error_line() const
>>> referenced by test_gdscript.cpp:1030 (main/tests/test_gdscript.cpp:1030)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1048 (main/tests/test_gdscript.cpp:1048)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptParser::get_error_column() const
>>> referenced by test_gdscript.cpp:1030 (main/tests/test_gdscript.cpp:1030)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1048 (main/tests/test_gdscript.cpp:1048)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptParser::get_error() const
>>> referenced by test_gdscript.cpp:1030 (main/tests/test_gdscript.cpp:1030)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))
>>> referenced by test_gdscript.cpp:1048 (main/tests/test_gdscript.cpp:1048)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: undefined symbol: GDScriptParser::get_parse_tree() const
>>> referenced by test_gdscript.cpp:1035 (main/tests/test_gdscript.cpp:1035)
>>>               lto.tmp:(TestGDScript::test(TestGDScript::TestType))

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.x11.tools.64.llvm] Error 1
scons: building terminated because of errors.

**Comment by arifnegh45** [comment]
once i build without LTO it works now.
