### ISSUE TITLE
[Question] Curious about the current state?

### ISSUE THREAD

**Issue by Muvkina** [perbone/luascript#36]
I saw the issue #1 but that is obviously quite outdated however you said you didn't think it was worth the effort is that still your stance? If it isn't is the project usable yet? Thank you so much for the hard work!

**Comment by perbone** [comment]
Hi! 

To be honest, I'm not sure it's worth spending more time developing this project. So far no one has had any real interest in discussing the issues I've raised so that the community could contribute. Yeah, maybe there were one or two guys, but that's not enough. The other problem is that I don't have a machine capable of running Vulkan, so I'm stuck with the 3.x branch which will probably be forgotten once 4.0 comes out.

So as you can see, there's not a lot of encouragement here.

Anyway, thanks for your interest.
- Perbone

**Comment by Poikilos** [comment]
@perbone Please consider hanging around longer. Many other people also don't have a machine that runs Vulkan, including a large share of mobile devices. That means 3.x will be relevant. I for one am developing games and won't give up that market share. New features are continually backported to 3.x.
